-- ELO V0.7 — SOLICITAÇÕES
create table if not exists public.solicitacoes (
  id uuid primary key default gen_random_uuid(),
  codigo bigint generated by default as identity unique,
  solicitante_id uuid not null references public.profiles(id) on delete restrict,
  responsavel_id uuid references public.profiles(id) on delete set null,
  titulo text not null,
  descricao text,
  categoria text,
  prioridade text not null default 'media'
    check (prioridade in ('baixa','media','alta','urgente')),
  prazo_desejado date,
  status text not null default 'nova'
    check (status in ('nova','em_analise','aprovada','recusada','demanda_gerada')),
  observacoes text,
  demanda_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_solicitacoes_solicitante on public.solicitacoes(solicitante_id);
create index if not exists idx_solicitacoes_responsavel on public.solicitacoes(responsavel_id);
create index if not exists idx_solicitacoes_status on public.solicitacoes(status);
create index if not exists idx_solicitacoes_prioridade on public.solicitacoes(prioridade);
create index if not exists idx_solicitacoes_created_at on public.solicitacoes(created_at desc);

drop trigger if exists trg_solicitacoes_updated_at on public.solicitacoes;
create trigger trg_solicitacoes_updated_at
before update on public.solicitacoes
for each row execute function public.set_updated_at();

alter table public.solicitacoes enable row level security;

drop policy if exists "solicitacoes_select" on public.solicitacoes;
create policy "solicitacoes_select" on public.solicitacoes for select to authenticated
using (public.is_active_user() and (public.is_admin() or public.has_permission('solicitacoes','view')));

drop policy if exists "solicitacoes_insert" on public.solicitacoes;
create policy "solicitacoes_insert" on public.solicitacoes for insert to authenticated
with check (public.is_active_user() and (public.is_admin() or public.has_permission('solicitacoes','create')));

drop policy if exists "solicitacoes_update" on public.solicitacoes;
create policy "solicitacoes_update" on public.solicitacoes for update to authenticated
using (public.is_active_user() and (public.is_admin() or public.has_permission('solicitacoes','edit')))
with check (public.is_active_user() and (public.is_admin() or public.has_permission('solicitacoes','edit')));

drop policy if exists "solicitacoes_delete" on public.solicitacoes;
create policy "solicitacoes_delete" on public.solicitacoes for delete to authenticated
using (public.is_active_user() and (public.is_admin() or public.has_permission('solicitacoes','delete')));

grant select, insert, update, delete on public.solicitacoes to authenticated;

do $$
begin
  if to_regclass('public.demandas') is not null then
    alter table public.demandas add column if not exists solicitacao_id uuid;
    create index if not exists idx_demandas_solicitacao_id on public.demandas(solicitacao_id);
    begin
      alter table public.demandas add constraint demandas_solicitacao_id_fkey
      foreign key (solicitacao_id) references public.solicitacoes(id) on delete set null;
    exception when duplicate_object then null;
    end;
  end if;
end $$;
