import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';
import logo from './assets/elo-logo.png';
import mark from './assets/elo-mark.png';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=(SUPABASE_URL&&SUPABASE_ANON_KEY)?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const nav=[['dashboard','Dashboard','⌂'],['demandas','Demandas','✓'],['solicitacoes','Solicitações','↗'],['ideias','Ideias','✦'],['projetos','Projetos','▣'],['arquivos','Arquivos','▤'],['destaques','Destaques','★'],['agenda','Agenda','◷'],['reunioes','Reuniões','◉'],['indicadores','Indicadores','▥']];
const data={demandas:[['Atualizar procedimento de atendimento','Alta','Mayara','Hoje','Em andamento'],['Relatório mensal de indicadores','Média','Rafael','30/09','Em análise'],['Treinamento da equipe','Média','Yasmin','03/10','Pendente'],['Melhoria do roteiro de atendimento','Baixa','Henrique','07/10','Em andamento']],solicitacoes:[['Verificar computador da recepção','Larissa','TI','Hoje','Em andamento'],['Troca de lâmpada da sala 2','Rafael','Manutenção','30/09','Pendente'],['Solicitar material de escritório','Yasmin','Administrativo','01/10','Em andamento'],['Acesso ao sistema de relatórios','Mayara','TI','02/10','Concluída']],ideias:[['Criar novo processo para reduzir tempo de espera','Henrique','Em análise','Alto'],['Implantar feedback digital do cliente','Mayara','Aprovada','Alto'],['Automatizar lembretes de reuniões','Rafael','Em desenvolvimento','Médio'],['Criar material de treinamento em vídeo','Yasmin','Em análise','Alto']],projetos:[['Novo processo de atendimento','Henrique','30/09','Em andamento'],['Implantação do sistema de relatórios','Rafael','15/10','Em andamento'],['Campanha interna de endomarketing','Mayara','25/10','Planejamento'],['Treinamento da equipe','Yasmin','05/11','Em andamento']]};
function Icon({children}){return <span className="icon">{children}</span>}
function Login({onLogin}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setError('');if(!supabase){setError('Configure VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY antes de usar o login.');return}setLoading(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error){setError('E-mail ou senha inválidos.');return}onLogin(data.session)};
 return <div className="loginPage"><div className="loginGlow"></div><div className="loginCard"><img src={logo} className="loginLogo"/><div className="loginBrand">ELO</div><p className="loginTag">GESTÃO • ORGANIZAÇÃO • RESULTADOS</p><div className="loginIntro"><h1>Acesso privado</h1><p>Entre com as credenciais fornecidas pelo administrador.</p></div><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" placeholder="seu@email.com"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" placeholder="••••••••"/></label>{error&&<div className="errorBox">{error}</div>}<button className="primary loginButton" disabled={loading}>{loading?'Entrando…':'Entrar no ELO'}</button></form><p className="loginFooter">Acesso restrito a usuários autorizados.</p></div></div>}
function App({session}){const [page,setPage]=useState('dashboard');const [menu,setMenu]=useState(false);const [light,setLight]=useState(false);const [showUsers,setShowUsers]=useState(false);const title=nav.find(n=>n[0]===page)?.[1]||'Dashboard';const email=session?.user?.email||'Usuário';const initials=email[0]?.toUpperCase()||'N';
 const logout=async()=>{if(supabase)await supabase.auth.signOut()};
 return <div className={light?'app light':'app'}><header className="topbar"><button className="menuBtn" onClick={()=>setMenu(true)} aria-label="Abrir menu"><span></span><span></span><span></span></button><div className="brand"><img src={mark}/><div><strong>ELO</strong><small>GESTÃO • ORGANIZAÇÃO • RESULTADOS</small></div></div><div className="topActions"><button className="ghost" onClick={()=>setLight(!light)}>{light?'☾':'☼'}</button><button className="bell">♧<i></i></button><div className="user"><div className="avatar">{initials}</div><div><b>{email}</b><small>Usuário autorizado</small></div></div></div></header><main className="main"><div className="heading"><div><p className="eyebrow">VISÃO GERAL</p><h1>{title}</h1><p className="muted">Acompanhe pessoas, ideias, demandas e resultados em um só lugar.</p></div>{page!=='dashboard'&&<button className="primary">＋ Nova ação</button>}</div>{page==='dashboard'&&<Dashboard/>}{page==='demandas'&&<TablePage rows={data.demandas} headers={['Título','Prioridade','Responsável','Prazo','Status']}/>} {page==='solicitacoes'&&<TablePage rows={data.solicitacoes} headers={['Solicitação','Solicitante','Área','Prazo','Status']}/>} {page==='ideias'&&<TablePage rows={data.ideias} headers={['Ideia','Autor','Status','Impacto']}/>} {page==='projetos'&&<TablePage rows={data.projetos} headers={['Projeto','Responsável','Prazo','Status']}/>} {['arquivos','destaques','agenda','reunioes','indicadores'].includes(page)&&<Placeholder page={title}/>} {showUsers&&<UserManager onClose={()=>setShowUsers(false)}/>}</main>{menu&&<><div className="overlay" onClick={()=>setMenu(false)}></div><aside className="drawer"><div className="drawerHead"><div className="brand"><img src={mark}/><div><strong>ELO</strong><small>GESTÃO • ORGANIZAÇÃO • RESULTADOS</small></div></div><button onClick={()=>setMenu(false)}>×</button></div><nav>{nav.map(([id,label,ic])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><Icon>{ic}</Icon>{label}</button>)}</nav><div className="drawerBottom"><button onClick={()=>{setShowUsers(true);setMenu(false)}}><Icon>♙</Icon> Usuários</button><button><Icon>⚙</Icon> Configurações</button><button onClick={logout}><Icon>↪</Icon> Sair</button><div className="profile"><div className="avatar">{initials}</div><div><b>{email}</b><small>Conta autenticada</small></div></div></div></aside></>}</div>}
function Dashboard(){return <section><div className="cards"><Stat n="12" t="Demandas pendentes" s="3 para hoje"/><Stat n="07" t="Projetos ativos" s="2 próximos do prazo"/><Stat n="03" t="Ideias em análise" s="1 nova hoje"/><Stat n="05" t="Solicitações novas" s="2 urgentes"/></div><div className="grid2"><div className="panel"><div className="panelTitle"><div><h3>Prioridades de hoje</h3><span>O que precisa de atenção agora</span></div><button className="link">Ver todas</button></div>{[['Atualizar procedimento de atendimento','Alta','Hoje'],['Relatório mensal de indicadores','Média','30/09'],['Reunião com equipe de supervisão','Média','Hoje'],['Finalizar projeto de melhoria','Baixa','02/10']].map((x,i)=><div className="priority" key={i}><span className={'dot d'+i}></span><div><b>{x[0]}</b><small>Prazo: {x[2]}</small></div><em>{x[1]}</em></div>)}</div><div className="panel highlight"><div className="panelTitle"><div><h3>🏆 Destaque do mês</h3><span>Reconhecimento da equipe</span></div></div><div className="highlightBody"><div className="personPic">★</div><div><h2>Reconhecimento da equipe</h2><p>Excelência no Atendimento</p><small>O destaque será alimentado pelo módulo de reconhecimento.</small></div></div><button className="secondary">Ver detalhes</button></div></div><div className="panel activity"><div className="panelTitle"><div><h3>Atividade recente</h3><span>Últimas movimentações</span></div></div>{['Nova demanda registrada','Projeto atualizado','Nova ideia adicionada','Arquivo compartilhado'].map((x,i)=><div className="activityRow" key={i}><span className="miniAvatar">{['N','P','I','A'][i]}</span><div><b>{x}</b><small>{i+1}h atrás</small></div></div>)}</div></section>}
function Stat({n,t,s}){return <div className="stat"><div className="statIcon">◈</div><div><strong>{n}</strong><b>{t}</b><small>{s}</small></div></div>}
function TablePage({rows,headers}){return <section className="panel tablePanel"><div className="toolbar"><div className="search">⌕ <input placeholder="Buscar..."/></div><button className="filter">☷ Filtros</button></div><div className="table"><div className="tr th">{headers.map(h=><span key={h}>{h}</span>)}<span></span></div>{rows.map((r,i)=><div className="tr" key={i}>{r.map((c,j)=><span key={j} className={j===r.length-1?'status':''}>{c}</span>)}<span className="more">•••</span></div>)}</div></section>}
function Placeholder({page}){return <section className="panel placeholder"><div className="bigIcon">◈</div><h2>{page}</h2><p>O módulo está preparado na estrutura inicial do ELO. Aqui entraremos com o fluxo completo, seguindo o mesmo padrão visual.</p><button className="primary">＋ Criar primeiro registro</button></section>}
function UserManager({onClose}){const [name,setName]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState('colaborador');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const create=async e=>{e.preventDefault();setBusy(true);setMsg('');if(!supabase){setMsg('Supabase não configurado.');setBusy(false);return}const {data:{session}}=await supabase.auth.getSession();const res=await supabase.functions.invoke('admin-create-user',{body:{name,email,role}});setBusy(false);setMsg(res.error?'Não foi possível criar o usuário. Verifique a Edge Function e as permissões.':'Usuário criado. A credencial inicial deverá ser definida pelo fluxo administrativo.');if(!res.error){setName('');setEmail('')}};return <div className="modalWrap"><div className="modal"><div className="modalHead"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Usuários ELO</h2><span>Criação interna de acessos</span></div><button onClick={onClose}>×</button></div><form onSubmit={create} className="userForm"><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value)}><option value="administrador">Administrador</option><option value="gestor">Gestor</option><option value="supervisor">Supervisor</option><option value="colaborador">Colaborador</option></select></label>{msg&&<div className="notice">{msg}</div>}<button className="primary" disabled={busy}>{busy?'Criando…':'Criar usuário internamente'}</button></form></div></div>}
function Root(){const [session,setSession]=useState(undefined);useEffect(()=>{if(!supabase){setSession(null);return}supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(session===undefined)return <div className="loading">Carregando ELO…</div>;if(!session)return <Login onLogin={setSession}/>;return <App session={session}/>}
createRoot(document.getElementById('root')).render(<Root/>);
